@startuml
title Use Registration Flow

actor User as User
participant "Auth Service" as AuthService
participant "SMS Gateway" as Smsgateway
database "Database" as DB

User -> AuthService: Phone number
AuthService -> Smsgateway: Phone number +\nCode

alt Invalid Phone Number
    Smsgateway --> AuthService: Error
    AuthService --> User: Error
else Correct Phone number
    Smsgateway --> User: Code in SMS
end

User -> AuthService: Code from SMS

alt Wrong Code
    AuthService --> User: Error
else Correct Code
    AuthService --> User: Success
end

User -> AuthService: username & password
AuthService -> DB: phone number\nusername\nencrypted password
AuthService -> User: User is registered

@enduml
